# Generated by Django 4.2.30 on 2026-08-16 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebles', '0019_unaccent_extension'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValuacionInmueble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_alquiler_min', models.DecimalField(decimal_places=2, help_text='Precio mínimo estimado de alquiler mensual (USD)', max_digits=12)),
                ('precio_alquiler_optimo', models.DecimalField(decimal_places=2, help_text='Precio sugerido óptimo de alquiler mensual (USD)', max_digits=12)),
                ('precio_alquiler_max', models.DecimalField(decimal_places=2, help_text='Precio máximo estimado de alquiler mensual (USD)', max_digits=12)),
                ('precio_venta_min', models.DecimalField(decimal_places=2, help_text='Precio mínimo estimado de venta (USD)', max_digits=14)),
                ('precio_venta_optimo', models.DecimalField(decimal_places=2, help_text='Precio sugerido óptimo de venta (USD)', max_digits=14)),
                ('precio_venta_max', models.DecimalField(decimal_places=2, help_text='Precio máximo estimado de venta (USD)', max_digits=14)),
                ('confianza_porcentaje', models.PositiveIntegerField(default=90, help_text='Porcentaje de confianza estadística del modelo (0-100%)')),
                ('roi_anual_estimado', models.DecimalField(decimal_places=2, default=8.0, help_text='Retorno sobre inversión estimado (%)', max_digits=6)),
                ('cap_rate_estimado', models.DecimalField(decimal_places=2, default=7.5, help_text='Tasa de capitalización anual (%)', max_digits=6)),
                ('dias_vacancia_estimados', models.PositiveIntegerField(default=15, help_text='Días promedio estimados que el inmueble pasa sin inquilino')),
                ('comparables_analizados', models.JSONField(blank=True, default=list, help_text='Lista de propiedades comparables analizadas en la zona')),
                ('analisis_mercado_ia', models.TextField(blank=True, help_text='Diagnóstico y recomendaciones de mercado redactadas por la IA')),
                ('fecha_calculo', models.DateTimeField(auto_now_add=True)),
                ('inmueble', models.ForeignKey(help_text='Inmueble evaluado', on_delete=django.db.models.deletion.CASCADE, related_name='valuaciones', to='inmuebles.inmueble')),
            ],
            options={
                'verbose_name': 'Valuación Automática',
                'verbose_name_plural': 'Valuaciones Automáticas',
                'db_table': 'inmuebles_valuacion',
                'ordering': ['-fecha_calculo'],
            },
        ),
        migrations.CreateModel(
            name='AmobladoVirtual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estilo', models.CharField(choices=[('moderno', 'Moderno'), ('minimalista', 'Minimalista'), ('ejecutivo', 'Ejecutivo'), ('boliviano', 'Boliviano')], db_index=True, default='moderno', max_length=30)),
                ('imagen_amoblada', models.CharField(help_text='URL de la imagen amoblada con IA (Cloudinary / CDN)', max_length=500)),
                ('descripcion_estilo', models.TextField(blank=True, help_text='Descripción de los elementos de diseño incorporados por la IA')),
                ('tipo', models.CharField(choices=[('foto_2d', 'Fotografía 2D'), ('panorama360', 'Panorama 360°')], default='foto_2d', max_length=20)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('inmueble', models.ForeignKey(help_text='Inmueble al que pertenece el amoblado virtual', on_delete=django.db.models.deletion.CASCADE, related_name='amoblados_virtuales', to='inmuebles.inmueble')),
                ('multimedia_original', models.ForeignKey(blank=True, help_text='Foto o panorama vacío original', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amoblados_generados', to='inmuebles.multimedia')),
            ],
            options={
                'verbose_name': 'Amoblado Virtual (Staging)',
                'verbose_name_plural': 'Amoblados Virtuales (Staging)',
                'db_table': 'inmuebles_amoblado_virtual',
                'ordering': ['-creado'],
            },
        ),
    ]
